# Generated by Django 2.1.7 on 2019-03-13 06:57

from django.db import migrations, models
import django.db.models.deletion
import user_contacts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[user_contacts.validators.validate_string])),
                ('last_name', models.CharField(max_length=30, validators=[user_contacts.validators.validate_string])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True, validators=[user_contacts.validators.validate_string])),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, validators=[user_contacts.validators.validate_number])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_contacts.Person')),
            ],
        ),
    ]
